# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='level',
            field=models.IntegerField(default=1, help_text='Level of the badge'),
        ),
        migrations.AddField(
            model_name='achievementprogress',
            name='progress',
            field=models.IntegerField(blank=True, default=None, help_text='Progress towards next level', null=True),
        ),
    ]
