# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_level_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='code',
            field=models.TextField(help_text='Internal reference code. Must also be valid as Python function name'),
        ),
    ]
