# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complete_checklist', models.BooleanField()),
                ('start_date_time', models.DateTimeField()),
                ('checklist_comments', models.TextField(blank=True)),
                ('number_of_observers', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(decimal_places=6, help_text='Distance in km', max_digits=16)),
                ('area', models.DecimalField(decimal_places=6, help_text='Area covered in ha', max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('state_province', models.TextField(help_text='State or province')),
                ('county', models.TextField(blank=True)),
                ('locality', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(null=True)),
                ('presence', models.BooleanField()),
                ('species_comments', models.TextField()),
                ('breeding_atlas_code', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('taxonomic_order', models.DecimalField(decimal_places=10, max_digits=20, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('scientific_name', models.TextField(unique=True)),
                ('common_name', models.TextField()),
                ('ioc_name', models.TextField()),
                ('order', models.TextField(blank=True)),
                ('family', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Species'),
        ),
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.Location'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
