# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.TextField(help_text='species, issf, etc'),
        ),
    ]
